services:
  selenoid:
    image: "aerokube/selenoid:latest"
    platform: linux/amd64
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    volumes:
      - ".:/etc/selenoid"
      - "./target:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./target:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/target"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-container-network", "selenoid",
              "-limit", "15", "-session-attempt-timeout", "180s", "-retry-count", "2", "-session-delete-timeout", "2m",
              "-service-startup-timeout", "3m"]

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    platform: linux/amd64
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "9090:8080"
    networks:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
  
  # Add this video recorder service
  video-recorder:
    image: "selenoid/video-recorder:latest-release"
    platform: linux/amd64
    container_name: selenoid-video-recorder
    networks:
      - selenoid
    volumes:
      - "./target:/opt/selenoid/video"
    environment:
      - "VIDEO_CONTAINER_NAME_PATTERN=selenoid-video-recorder-*"
    command: ["--log-output-dir", "/opt/selenoid/video"]
    
  chrome_124.0:
    image: "selenoid/vnc:chrome_124.0"
    platform: linux/amd64
    container_name: chrome_124.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
  chrome_113.0:
    image: "selenoid/vnc:chrome_113.0"
    platform: linux/amd64
    container_name: chrome_113.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
  chrome_123.0:
    image: "selenoid/vnc:chrome_123.0"
    platform: linux/amd64
    container_name: chrome_123.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
  chrome_126.0:
    image: "selenoid/vnc:chrome_126.0"
    platform: linux/amd64
    container_name: chrome_126.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"          

  firefox_125.0:
    image: "selenoid/vnc:firefox_125.0"
    platform: linux/amd64
    container_name: firefox_125.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
  firefox_124.0:
    image: "selenoid/vnc:firefox_124.0"
    platform: linux/amd64
    container_name: firefox_124.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
  firefox_100.0:
    image: "selenoid/vnc:firefox_100.0"
    platform: linux/amd64
    container_name: firefox_100.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
  firefox_105.0:
    image: "selenoid/vnc:firefox_105.0"
    platform: linux/amd64
    container_name: firefox_105.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"    
                    
networks:
  selenoid:
    name: selenoid
    external: true

