qa:
  login_url: "https://naveenautomationlabs.com/opencart/index.php?route=account/login"
  browser: "chrome"
  test_data:
    user_registration: "test_data/user_registration_data.csv"
  credentials:
    email: "monty.pompy@gmail.com"
    password: "monty_pompy"
  headless: false
  incognito: true
  flash: true
  remote:
    enabled: true
    remote_url: "http://localhost:4444/wd/hub"

uat:
  login_url: "https://naveenautomationlabs.com/opencart/index.php?route=account/login"
  browser: "edge"
  test_data:
    user_registration: "test_data/user_registration_data.csv"
  credentials:
    email: "testuser_12@gmail.com"
    password: "Welcome11@"
  headless: false
  incognito: true
  flash: true

prod:
  base_url: "https://naveenautomationlabs.com/opencart/index.php?route=account/login"
  browser: "chrome"
  credentials:
    username: "prod@example.com"
    password: "prodpass"
